### PR TITLE
Add MessageBodyTemplate

### PR DESCRIPTION
**Pull request by devanych**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Fixed issues  | https://github.com/yiisoft/mailer-swiftmailer/issues/33

### CODE REVIEW

**Comment by samdark** [comment]
⚠️ Do not merge w/o additional mailer-swiftmailer PR adjusting config.

**Comment by samdark** [comment]
Looks alright. Should it be reflected in README somehow?

**Comment by devanych** [comment]
> Looks alright. Should it be reflected in README somehow?

I think no, I will add a description to the guide after the merge.

**Comment by samdark** [comment]
OK. Then the only part left is the config

**Pull request merged**
